//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int cardId { get; set; }
        public int accountId { get; set; }
        public int cardNumber { get; set; }
        public System.DateTime expiryDate { get; set; }
        public int CVV { get; set; }
        public string status { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
